[package]
name = "day13"
version = "0.1.0"
authors = ["18551877+GrumpyMetalGuy@users.noreply.github.com"]
edition = "2018"

[dependencies]
utils = { path = "../utils"}
simple-matrix = "0.1"
uuid = { version = "0.7", features = ["v4"] }
